### ISSUE TITLE
no main manifest attribute, in jbehave-to-gherkin-1.0.1-SNAPSHOT.jar

### ISSUE THREAD

**Issue by snowch** [seize-the-dave/jbehave-to-gherkin#6]
I ran into the error using the instructions in the README.md

`no main manifest attribute, in jbehave-to-gherkin-1.0.1-SNAPSHOT.jar`

It was easy for me to fix by pointing to jbehave-to-gherkin-1.0.1-SNAPSHOT-jar-with-dependencies.jar, but may cause a non-java user some headaches.

Also would be good to give a jar download as a non-java user may struggle with building.

**Comment by seize-the-dave** [comment]
Thanks @snowch, will take a look at the missing manifest.

**Comment by seize-the-dave** [comment]
Released in v1.0.1.
