### ISSUE TITLE
Enhancement: recursively convert stories in a folder and its subfolders 

### ISSUE THREAD

**Issue by snowch** [seize-the-dave/jbehave-to-gherkin#7]
It would be great if the app could traverse a folder and its subfolders and convert all stories that it finds.

In the meantime, I have used a shell script to do this:

```
#!/bin/bash

if [ $# -lt 2 ]
then
   echo -e "Usage: $0 jarname storydir"
   exit 1
fi

JAR=$1
STORY_DIR=$2

STORIES=$(find $STORY_DIR -name *.story)
for STORY in ${STORIES[*]}
do
  FEATURE=$(echo $STORY | sed 's/\.story$/\.feature/g')
  echo "Creating $FEATURE"
  java -jar $JAR < $STORY > $FEATURE 
done
```

**Comment by seize-the-dave** [comment]
The philosophy of the project is to the least possible, so as long as a feature can be accomplished by existing tools, I'm not going to add it in.
